import React, { useState, useEffect } from "react";
import Navbar from "../components/Navbar";
import ProductCard from "../components/ProductCard";
import { useNavigate } from "react-router-dom";
import { ChevronRight } from "lucide-react";
import RecommendationSection from "../components/RecommendationSection";
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@/components/ui/carousel";

const Index = () => {
  const navigate = useNavigate();
  const [featuredProducts, setFeaturedProducts] = useState([]);
  const [newArrivals, setNewArrivals] = useState([]);
  const [personalizedRecommendations, setPersonalizedRecommendations] = useState([]);

  // Mock featured products data (would be fetched from an API)
  const mockFeaturedProducts = [
    {
      id: 1,
      name: "Classic Fit T-Shirt",
      category: "men",
      price: 29.99,
      originalPrice: 39.99,
      brand: "Nike",
      color: "Blue",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?q=80&w=500&auto=format&fit=crop",
      rating: 4.5,
    },
    {
      id: 2,
      name: "Floral Summer Dress",
      category: "women",
      price: 49.99,
      originalPrice: 69.99,
      brand: "Zara",
      color: "Pink",
      sizes: ["XS", "S", "M", "L"],
      image: "https://images.unsplash.com/photo-1612336307429-8a898d10e223?q=80&w=500&auto=format&fit=crop",
      rating: 4.2,
    },
    {
      id: 5,
      name: "Running Sneakers",
      category: "footwear",
      price: 89.99,
      originalPrice: 119.99,
      brand: "Adidas",
      color: "Black",
      sizes: ["7", "8", "9", "10", "11"],
      image: "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=500&auto=format&fit=crop",
      rating: 4.7,
    },
    {
      id: 7,
      name: "Silver Necklace",
      category: "accessories",
      price: 59.99,
      originalPrice: 59.99,
      brand: "Pandora",
      color: "Silver",
      sizes: ["One Size"],
      image: "https://images.unsplash.com/photo-1611085583191-a3b181a88552?q=80&w=500&auto=format&fit=crop",
      rating: 4.3,
    },
  ];

  // Mock new arrivals (would be fetched from an API)
  const mockNewArrivals = [
    {
      id: 9,
      name: "Lightweight Windbreaker",
      category: "men",
      price: 69.99,
      originalPrice: 89.99,
      brand: "Columbia",
      color: "Gray",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=500&auto=format&fit=crop",
      rating: 4.3,
    },
    {
      id: 10,
      name: "Casual Slip-On Shoes",
      category: "footwear",
      price: 49.99,
      originalPrice: 49.99,
      brand: "Vans",
      color: "White",
      sizes: ["7", "8", "9", "10", "11"],
      image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=500&auto=format&fit=crop",
      rating: 4.0,
    },
    {
      id: 11,
      name: "Premium Jogger Pants",
      category: "men",
      price: 45.99,
      originalPrice: 59.99,
      brand: "Under Armour",
      color: "Black",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.unsplash.com/photo-1616257460948-66176612b9d9?q=80&w=500&auto=format&fit=crop",
      rating: 4.6,
    },
    {
      id: 12,
      name: "Smart Watch",
      category: "accessories",
      price: 199.99,
      originalPrice: 249.99,
      brand: "Garmin",
      color: "Black",
      sizes: ["One Size"],
      image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?q=80&w=500&auto=format&fit=crop",
      rating: 4.9,
    },
  ];

  // Mock personalized recommendations (would be generated by AI)
  const mockPersonalizedRecommendations = [
    {
      id: 13,
      name: "Leather Crossbody Bag",
      category: "accessories",
      price: 79.99,
      originalPrice: 99.99,
      brand: "Coach",
      color: "Tan",
      sizes: ["One Size"],
      image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=500&auto=format&fit=crop",
      rating: 4.7,
    },
    {
      id: 14,
      name: "Wireless Earbuds",
      category: "accessories",
      price: 129.99,
      originalPrice: 159.99,
      brand: "JBL",
      color: "Black",
      sizes: ["One Size"],
      image: "https://images.unsplash.com/photo-1606220838315-056192d5e927?q=80&w=500&auto=format&fit=crop",
      rating: 4.5,
    },
    {
      id: 15,
      name: "Casual Denim Jacket",
      category: "women",
      price: 69.99,
      originalPrice: 89.99,
      brand: "Levi's",
      color: "Blue",
      sizes: ["XS", "S", "M", "L"],
      image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=500&auto=format&fit=crop",
      rating: 4.4,
    },
    {
      id: 16,
      name: "Aviator Sunglasses",
      category: "accessories",
      price: 119.99,
      originalPrice: 119.99,
      brand: "Ray-Ban",
      color: "Gold",
      sizes: ["One Size"],
      image: "https://images.unsplash.com/photo-1577803645773-f96470509666?q=80&w=500&auto=format&fit=crop",
      rating: 4.8,
    },
  ];

  // Simulate fetching data
  useEffect(() => {
    // In a real application, these would be API calls
    setFeaturedProducts(mockFeaturedProducts);
    setNewArrivals(mockNewArrivals);
    setPersonalizedRecommendations(mockPersonalizedRecommendations);
  }, []);

  const fashionQuotes = [
    {
      quote: "Style is a way to say who you are without having to speak",
      author: "Rachel Zoe",
      image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1200&auto=format&fit=crop"
    },
    {
      quote: "Fashion is the armor to survive the reality of everyday life",
      author: "Bill Cunningham",
      image: "https://images.unsplash.com/photo-1445205170230-053b83016050?q=80&w=1200&auto=format&fit=crop"
    },
    {
      quote: "Fashion is about dressing according to what's fashionable. Style is more about being yourself",
      author: "Oscar de la Renta",
      image: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1200&auto=format&fit=crop"
    }
  ];

  return (
    <div className="min-h-screen bg-trendify-lightGray">
      <Navbar />
      
      {/* Hero Section with Fashion Quote Slider */}
      <section className="relative bg-gradient-to-r from-trendify-teal to-teal-700 text-white">
        <Carousel className="w-full" opts={{ loop: true }}>
          <CarouselContent>
            {fashionQuotes.map((item, index) => (
              <CarouselItem key={index}>
                <div className="relative h-[500px] w-full">
                  <div className="absolute inset-0">
                    <img 
                      src={item.image} 
                      alt={`Fashion ${index + 1}`} 
                      className="w-full h-full object-cover opacity-40"
                    />
                  </div>
                  <div className="relative h-full flex items-center justify-center">
                    <div className="text-center max-w-4xl mx-auto px-4">
                      <p className="text-3xl md:text-4xl font-serif italic mb-4">
                        "{item.quote}"
                      </p>
                      <p className="text-xl font-light">- {item.author}</p>
                    </div>
                  </div>
                </div>
              </CarouselItem>
            ))}
          </CarouselContent>
          <div className="absolute inset-x-4 top-1/2 flex items-center justify-between -translate-y-1/2">
            <CarouselPrevious className="bg-white/80 hover:bg-white" />
            <CarouselNext className="bg-white/80 hover:bg-white" />
          </div>
        </Carousel>
      </section>

      {/* Categories Section */}
      <section className="py-16 px-4">
        <div className="container mx-auto max-w-6xl">
          <h2 className="text-3xl font-bold mb-8 text-center">Shop by Category</h2>
          
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { name: "Men", image: "https://images.unsplash.com/photo-1516826957135-700dedea698c?q=80&w=387&auto=format&fit=crop", path: "/shop/men" },
              { name: "Women", image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=387&auto=format&fit=crop", path: "/shop/women" },
              { name: "Kids", image: "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?q=80&w=387&auto=format&fit=crop", path: "/shop/kids" },
              { name: "Accessories", image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=387&auto=format&fit=crop", path: "/shop/accessories" },
            ].map((category) => (
              <div
                key={category.name}
                onClick={() => navigate(category.path)}
                className="relative overflow-hidden rounded-lg shadow-md cursor-pointer group h-48 md:h-64"
              >
                <img
                  src={category.image}
                  alt={category.name}
                  className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-300"
                />
                <div className="absolute inset-0 bg-black bg-opacity-40 flex items-center justify-center group-hover:bg-opacity-60 transition-all">
                  <h3 className="text-white text-xl font-bold">{category.name}</h3>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
      
      {/* Featured Products Section */}
      <section className="py-12 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="flex justify-between items-center mb-8">
            <h2 className="text-2xl font-bold">Featured Products</h2>
            <button 
              onClick={() => navigate("/shop")}
              className="flex items-center gap-1 text-trendify-teal hover:underline"
            >
              View all <ChevronRight size={16} />
            </button>
          </div>
          
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {featuredProducts.map((product) => (
              <ProductCard key={product.id} product={product} />
            ))}
          </div>
        </div>
      </section>
      
      {/* New Arrivals Section */}
      <section className="py-12 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="flex justify-between items-center mb-8">
            <h2 className="text-2xl font-bold">New Arrivals</h2>
            <button 
              onClick={() => navigate("/shop")}
              className="flex items-center gap-1 text-trendify-teal hover:underline"
            >
              View all <ChevronRight size={16} />
            </button>
          </div>
          
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {newArrivals.map((product) => (
              <ProductCard key={product.id} product={product} />
            ))}
          </div>
        </div>
      </section>
      
      {/* AI Recommendation Section */}
      <RecommendationSection 
        title="Recommended For You" 
        description="Based on your browsing history and preferences"
        products={personalizedRecommendations}
      />
      
      {/* Newsletter Section */}
      <section className="py-16 px-4 bg-gray-100">
        <div className="container mx-auto max-w-6xl">
          <div className="bg-white p-8 rounded-lg shadow-sm">
            <div className="text-center max-w-xl mx-auto">
              <h3 className="text-2xl font-bold mb-2">Subscribe to our newsletter</h3>
              <p className="text-gray-600 mb-6">
                Get the latest updates on new products and upcoming sales
              </p>
              
              <form className="flex flex-col sm:flex-row gap-2">
                <input
                  type="email"
                  placeholder="Your email address"
                  className="flex-grow border border-gray-300 rounded-md px-4 py-2 focus:outline-none focus:ring-2 focus:ring-trendify-teal"
                  required
                />
                <button
                  type="submit"
                  className="bg-trendify-teal text-white px-6 py-2 rounded-md font-medium hover:bg-opacity-90 transition-colors"
                >
                  Subscribe
                </button>
              </form>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Index;
